{{- if .Values.role.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ include "common.names.namespace" . }}
  name: {{ include "localstack.roleName" . }}
  labels:
    {{- include "localstack.labels" . | nindent 4 }}
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "services"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["get", "create"]
- apiGroups: ["apps"]
  resources: ["deployments", "deployments/scale"]
  verbs: ["*"]
{{- if .Values.role.extraRoles }}
{{ include "common.tplvalues.render" (dict "value" .Values.role.extraRoles "context" $) }}
{{- end }}
{{- end }}

