annotations:
  category: Infrastructure
apiVersion: v2
appVersion: latest
version: 0.6.0
name: localstack
description: LocalStack - a fully functional local AWS cloud stack
type: application
keywords:
  - aws
  - localstack
sources:
- https://localstack.cloud/
- https://github.com/localstack/localstack
icon: https://localstack.cloud/images/localstack.png
maintainers:
- name: LocalStack Team and Community
  email: info@localstack.cloud
dependencies:
  - name: common
    version: 2.2.4
    repository: https://charts.bitnami.com/bitnami
